#!/usr/bin/env python3
"""Builds docs/charts/*.png and docs/results.md from bench/results/*.csv (medians)."""
import csv, os, statistics
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

R, OUT = "bench/results", "docs/charts"
ORDER = ["wasm", "container", "python"]
LABEL = {"wasm": "WASM (Spin)", "container": "Rust container", "python": "Python container"}
COLOR = {"wasm": "#7c3aed", "container": "#0ea5e9", "python": "#f59e0b"}
MIB = 1024 * 1024
os.makedirs(OUT, exist_ok=True)


def read(name):
    with open(f"{R}/{name}") as f:
        return list(csv.DictReader(f))


def fnum(x):
    try:
        v = float(x)
        return v if v == v else None
    except (TypeError, ValueError):
        return None


def med(rows, wl, key):
    vals = [fnum(r[key]) for r in rows if r["workload"] == wl]
    vals = [v for v in vals if v is not None]
    return statistics.median(vals) if vals else 0.0


def grouped(ax, groups, values, ylabel, fmt="{:.0f}"):
    n = len(ORDER)
    width = 0.8 / n
    for i, s in enumerate(ORDER):
        xs = [g - 0.4 + width / 2 + i * width for g in range(len(groups))]
        bars = ax.bar(xs, values[s], width, label=LABEL[s], color=COLOR[s])
        for b in bars:
            ax.annotate(fmt.format(b.get_height()), (b.get_x() + b.get_width() / 2, b.get_height()),
                        ha="center", va="bottom", fontsize=8)
    ax.set_xticks(range(len(groups)))
    ax.set_xticklabels(groups)
    ax.set_ylabel(ylabel)
    ax.legend()
    ax.grid(axis="y", alpha=0.3)


def save(fig, name):
    fig.tight_layout()
    fig.savefig(f"{OUT}/{name}", dpi=150)
    plt.close(fig)
    print("wrote", f"{OUT}/{name}")


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


md = ["# Results (auto-generated by bench/make_charts.py)\n"]

# 1. runtime-level cold start (no Kubernetes)
rs = read("runtime_start.csv")
vals = [med(rs, w, "first_200_ms") for w in ORDER]
fig, ax = plt.subplots(figsize=(6, 4))
bars = ax.bar([LABEL[w] for w in ORDER], vals, color=[COLOR[w] for w in ORDER])
for b in bars:
    ax.annotate(f"{b.get_height():.0f}", (b.get_x() + b.get_width() / 2, b.get_height()), ha="center", va="bottom")
ax.set_ylabel("ms (median), launch -> first HTTP 200")
ax.set_title("Cold start WITHOUT Kubernetes")
ax.grid(axis="y", alpha=0.3)
save(fig, "1-runtime-cold-start.png")
md.append("## Cold start without Kubernetes (median ms)\n")
md.append(table(["workload", "launch -> first 200"], [[LABEL[w], f"{v:.1f}"] for w, v in zip(ORDER, vals)]))

# 2. Kubernetes pod cold start (scale 0 -> 1, image pre-pulled)
cs = read("coldstart.csv")
mets = ["running", "first_200", "ready"]
fig, ax = plt.subplots(figsize=(7, 4))
grouped(ax, mets, {w: [med(cs, w, m) for m in mets] for w in ORDER}, "ms (median)")
ax.set_title("Pod cold start on K3s (scale 0 -> 1)")
save(fig, "2-k8s-pod-cold-start.png")
md.append("## Pod cold start on K3s, 0 -> 1 (median ms)\n")
md.append(table(["workload", *mets], [[LABEL[w], *[f"{med(cs, w, m):.0f}" for m in mets]] for w in ORDER]))

# 3. scale-from-zero through the KEDA HTTP add-on
sz = read("scale_from_zero.csv")
mets = ["total_ms", "keda_scaled", "running", "ready"]
names = ["request -> response", "KEDA scaled", "pod Running", "pod Ready"]
fig, ax = plt.subplots(figsize=(8, 4))
grouped(ax, names, {w: [med(sz, w, m) for m in mets] for w in ORDER}, "ms (median)")
ax.set_title("Scale-from-zero via KEDA HTTP add-on")
save(fig, "3-scale-from-zero.png")
md.append("## Scale from zero via KEDA HTTP add-on (median ms)\n")
md.append(table(["workload", *names, "warm request"],
                [[LABEL[w], *[f"{med(sz, w, m):.0f}" for m in mets], f"{med(sz, w, 'warm_ms'):.1f}"] for w in ORDER]))

# 4. memory footprint
mem = read("memory.csv")


def mval(w, phase, key):
    for r in mem:
        if r["workload"] == w and r["phase"] == phase:
            return float(r[key]) / MIB
    return 0.0


fig, axes = plt.subplots(1, 2, figsize=(11, 4), sharey=True)
for ax, phase in zip(axes, ["idle", "load"]):
    grouped(ax, ["cgroup working set", "process PSS (shim + app)"],
            {w: [mval(w, phase, "cg_working_set"), mval(w, phase, "proc_pss")] for w in ORDER},
            "MiB", fmt="{:.1f}")
    ax.set_title(f"Memory: {phase}" + (" (wrk c=20, 30s)" if phase == "load" else ""))
save(fig, "4-memory.png")
md.append("## Memory (MiB)\n")
md.append(table(["workload", "phase", "cgroup working set", "cgroup anon", "cgroup peak", "process PSS", "#procs"],
                [[LABEL[r["workload"]], r["phase"], f"{float(r['cg_working_set'])/MIB:.2f}", f"{float(r['cg_anon'])/MIB:.2f}",
                  f"{float(r['cg_peak'])/MIB:.2f}", f"{float(r['proc_pss'])/MIB:.2f}", r["nprocs"]] for r in mem]))

# 5. edge simulation: 512Mi ResourceQuota
dn = read("density.csv")
quota = [r for r in dn if r["phase"] == "quota"]
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
qw = [r["workload"] for r in quota]
axes[0].bar([LABEL[w] for w in qw], [float(r["ready"]) for r in quota], color=[COLOR[w] for w in qw])
axes[0].set_title("Ready pods under a 512Mi ResourceQuota")
axes[1].bar([LABEL[w] for w in qw], [float(r["per_pod_host_mib"]) for r in quota], color=[COLOR[w] for w in qw])
axes[1].set_title("Host RAM per pod (MiB), measured via MemAvailable")
for ax in axes:
    ax.grid(axis="y", alpha=0.3)
    for b in ax.patches:
        ax.annotate(f"{b.get_height():.1f}", (b.get_x() + b.get_width() / 2, b.get_height()), ha="center", va="bottom")
save(fig, "5-edge-quota-density.png")
md.append("## Edge simulation: 512Mi ResourceQuota\n")
md.append(table(["workload", "pods Ready", "host RAM delta (MiB)", "host per pod (MiB)", "cgroup per pod (MiB)", "note"],
                [[LABEL[r["workload"]], r["ready"], r["host_delta_mib"], r["per_pod_host_mib"], r["per_pod_cgroup_mib"], r["note"]]
                 for r in quota]))
md.append("### Replica sweep (raw; small-N rows are dominated by MemAvailable noise)\n")
md.append(table(["workload", "N", "ready", "host delta (MiB)", "host/pod", "cgroup/pod"],
                [[LABEL[r["workload"]], r["target"], r["ready"], r["host_delta_mib"], r["per_pod_host_mib"], r["per_pod_cgroup_mib"]]
                 for r in dn if r["phase"] == "sweep"]))

# 6. memory-limit sweep
el = read("edge_limits.csv")
md.append("## Minimum memory limit sweep (wrk c=20, 15 s)\n")
md.append(table(["workload", "limit (MiB)", "verdict", "req/s", "restarts", "reason"],
                [[LABEL[r["workload"]], r["limit_mib"], r["verdict"], r["rps"], r["restarts"], r["reason"] or "-"] for r in el]))

open("docs/results.md", "w").write("\n".join(md))
print("wrote docs/results.md")
